name: TestWorkflow

on:
  push:
    branches:
      - main
      - another-branch-to-run-workflows-in
    tags:
      - "v*.*.*"
env:
  shouldDeployToDevelop: "true"

  shouldDeployToMaster:
    "false"
    # If the ref pushed is etiher staging or contains tags and the word hotfix
  shouldDeployToStaging: "false"
jobs:
  if: ${{ shouldDeployToDevelop == 'true' }}
  # commen
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        run: |
          echo "hello"
