name: TestWorkflow

on:
  push:
    branches:
      - main
jobs:
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        run: echo "${{ contains(github.ref, 'v*.*.*') && !contains(github.ref, 'hotfix') && !contains(github.ref, 'master') }}"
