name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
env:
  shouldDeployToDevelop: "true"
      # If the ref pushed is master deploy to prod
  shouldDeployToMaster: "false"
      # If the ref pushed is etiher staging or contains tags and the word hotfix
  shouldDeployToStaging: "false"
jobs:
  # commen
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        run: |
          echo "hello"
     
