name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
env:
  shouldDeployToDevelop: "true"
      # If the ref pushed is master deploy to prod
  shouldDeployToMaster: "false"
      # If the ref pushed is etiher staging or contains tags and the word hotfix
  shouldDeployToStaging: "false"
jobs:
  # comment
  TestJob:
    if: matrix.config.shouldRun == 'true'
    strategy:
      matrix:
        config:
        -  {AWS_ENV: 'dev', AWS_ACCOUNT_NR: '572577926476', shouldRun: "${{contains(github.ref, 'tags')}}" }
        -  {AWS_ENV: 'fina', AWS_ACCOUNT_NR: '572577926476', shouldRun: "${{'a' == 'a'}}" }
        -  {AWS_ENV: 'prod', AWS_ACCOUNT_NR: '521091457580', shouldRun: "${{contains(github.ref, 'tags')}}" }
        -  {AWS_ENV: 'staging', AWS_ACCOUNT_NR: '521091457580', shouldRun: "${{contains(github.ref, 'tags')}}" }
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        id: TestStep
        run: |
          echo "${{ matrix.config.AWS_ENV }}"
          echo "${{ matrix.config.shouldRun }}"
      - name: TestStep2
        if: fromJson(matrix.config.shouldRun)
        run: |
          echo "hello"
     
