name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  # comment
  TestJob:
    env:
      shouldDeployToDevelop: "true"
      # If the ref pushed is master deploy to prod
      shouldDeployToMaster: "false"
      # If the ref pushed is etiher staging or contains tags and the word hotfix
      shouldDeployToStaging: "false"
    strategy:
      matrix:
        config:
        -  {AWS_ENV: 'dev', AWS_ACCOUNT_NR: '572577926476', shouldRun: '${{shouldDeployToStaging == "true"}}' }
        -  {AWS_ENV: 'fina', AWS_ACCOUNT_NR: '572577926476', shouldRun: '${{shouldDeployToStaging == "false"}}' }
        -  {AWS_ENV: 'prod', AWS_ACCOUNT_NR: '521091457580', shouldRun: '${{shouldDeployToStaging == "false"}}' }
        -  {AWS_ENV: 'staging', AWS_ACCOUNT_NR: '521091457580', shouldRun: '${{shouldDeployToStaging == "false"}}' }
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        id: TestStep
        run: |
          echo "${{ matrix.config.AWS_ENV }}"
          echo "${{ matrix.config.shouldRun }}"
      - name: TestStep2
        if: fromJson(matrix.config.shouldRun)
        run: |
          echo "hello"
     
