name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  # comment
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        id: TestStep
        run: |
          echo "::set-output name=test::true"
          echo "::set-output name=test2::false"
      - name: TestStep2
        env: 
          testi: ${{ steps.TestStep.outputs.test && 'blä1' || 'buu1' }}
          testi2: ${{ fromJSON(steps.TestStep.outputs.test2) && 'blä4' || 'buu4' }}
        run: |
          echo "${{ env.testi }}"
          echo "${{ steps.TestStep.outputs.test2 }}"
          echo "${{ env.testi2 }}"
