name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  # comment
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        run: |
          echo "${{ github.ref }}"
          echo "${{ contains(github.ref, 'v') && !contains(github.ref, 'hotfix') && !contains(github.ref, 'main') }}"
          echo "${{ contains(github.ref, 'v*.*.*') && !contains(github.ref, 'hotfix') && !contains(github.ref, 'main') }}"
          echo "${{ toJSON(github) }}"
