name: TestWorkflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  # comment
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        env: 
          test: "true"
          test2: "false"
        run: |
          echo "${{ env.test && "blä2" || "buu2" }}"
          echo "${{ !env.test2 && "blä3" || "buu3" }}"
          echo "${{ env.test2 && "blä4" || "buu4" }}"
      - name: TestStep2
        env: 
          testi: ${{ env.test == true && "blä1" || "buu1" }}
          testi2: ${{ env.test2 && "blä4" || "buu4" }}
        run: |
          echo "${{ env.testi }}"
          echo "${{ env.testi2 }}"
