# This is a basic workflow to help you get started with Actions

name: triggered from another

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  workflow_run:
    workflows: ["TestWorkflow"]
    branches:
      - main
      - another-branch-to-run-workflows-in
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "${{toJSON(github.event.workflow_run.head_branch)}}"
