name: WorkflowOne

on:
  push:
    branches:
      - main
      - another-branch-to-run-workflows-in
    tags:
      - "v*.*.*"
jobs:
  # commen
  TestJob:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        run: |
          echo "hello"
